version = "0.1.2"
content_dir = "terms"

[pdf.merge]
spine = ["*.typ"]
title = "Critical terms for artificially intelligent life"

[epub.merge]
spine = ["*.typ"]
title = "Critical terms for artificially intelligent life"
